@host=https://localhost:7149

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Kiet",
    "lastName": "Duong Hung",
    "email": "kietduonghung@outlook.com",
    "password": "P@sswo4d"
}
